language: php

php:
  - 7.1
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
 - vendor/bin/phpcs -s
 - vendor/bin/php-cs-fixer fix --diff --dry-run
 - vendor/bin/phpunit --colors --coverage-text --coverage-clover=coverage.clover
